# Generated by Django 3.1.2 on 2021-08-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fieldworker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fieldworker',
                'managed': False,
            },
        ),
    ]
